name: wdb106_sample
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.17.0'
  flutter: '>=2.10.0'
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  go_router:
  hooks_riverpod:
  http:
  meta:
  simple_logger:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  go_router_builder:
  image_test_utils:
    git:
      url: https://github.com/mono0926/image_test_utils.git
      ref: add-compressionState
  json_serializable:
  mockito:
  pedantic_mono:
flutter:
  uses-material-design: true
