name: wdb106_sample
description: A new Flutter project.
version: 1.0.0+1
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  hooks_riverpod:
  rxdart:
  simple_logger:
  flutter_hooks:
  disposable_provider:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  image_test_utils:
  json_serializable:
  mockito:
  pedantic_mono:
flutter:
  uses-material-design: true